### ISSUE TITLE
/compat/linux/bin/edge: line 9: /usr/bin/microsoft-edge-dev: No such file or directory

### ISSUE THREAD

**Issue by Marietto2008** [mrclksr/linux-browser-installer#21]
Hello.

I'm trying to run the edge browser following the tutorial : [https://forums.freebsd.org/threads/...-google-chrome-linux-binary-on-freebsd.77559/](https://forums.freebsd.org/threads/linuxulator-how-to-run-google-chrome-linux-binary-on-freebsd.77559/)

so,I've folllowed that tutorial,with some minor changes. For example,I've created the custom edge launcher script called /compat/linux/bin/edge and I made it executable:

```
#!/compat/linux/bin/bash
export EDGE_PATH="/usr/bin/microsoft-edge-dev"
export EDGE_WRAPPER="`readlink -f "$0"`"
export LD_LIBRARY_PATH=/usr/local/steam-utils/lib64/fakeudev
export LD_PRELOAD=/usr/local/steam-utils/lib64/webfix/webfix.so
export LIBGL_DRI3_DISABLE=1
exec -a "$0" "$EDGE_PATH" --no-sandbox --no-zygote --test-type --v=0 "$@"
```

and I've created this desktop file to launch edge as any other app:

```
[Desktop Entry]
Type=Application
Version=1.0
Encoding=UTF-8
Name=Edge
Comment=Edge web browser
Icon=edge
Exec=/compat/linux/bin/edge
Categories=Application;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
StartupNotify=true
```

unfortunately when I execute it,I get the following error message :

```
@marietto:/home/marietto/Desktop/Browsers # /compat/linux/bin/edge
/compat/linux/bin/edge: line 9: /usr/bin/microsoft-edge-dev: No such file or directory
```

I don't know why,since the microsoft-edge-dev file is located on /compat/linux/usr/bin :

```
@marietto:/home/marietto/Desktop/Browsers # find /compat/linux/usr/bin -name microsoft-edge-dev
/compat/linux/usr/bin/microsoft-edge-dev
```

and the wrapper called edge is located on /compat/linux/bin

```
marietto:/home/marietto/Desktop/Browsers # find /compat/linux/bin -name edge
/compat/linux/bin/edge
```

**Comment by mrclksr** [comment]
Hi @Marietto2008,

this is not the right place for your question, but if you want to install Microsoft Edge:

```
$ git clone https://github.com/mrclksr/linux-browser-installer.git
$ cd linux-browser-installer
$ sudo ./linux-browser-installer install edge
```

If you want to install it manually, see the files [bin/linux-edge.in](https://github.com/mrclksr/linux-browser-installer/blob/main/bin/linux-edge.in), [chroot/bin/edge.in](https://github.com/mrclksr/linux-browser-installer/blob/main/chroot/bin/edge.in), and 
[linux-edge.desktop](https://github.com/mrclksr/linux-browser-installer/blob/main/linux-edge.desktop) for inspiration.

**Comment by Marietto2008** [comment]
```
root@marietto:/usr/home/marietto/Desktop/Scripts/linux-browser-installer # sudo ./linux-browser-installer install edge
[: missing ]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.68.0-1ubuntu2).
apt-transport-https is already the newest version (2.0.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
15 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up python3 (3.8.2-0ubuntu2) ...
running python rtupdate hooks for python3.8...
dpkg-query: package 'apt-xapian-index' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of apt-xapian-index
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 620, in add_proc_info
    ret = self.get_logind_session(pid, proc_pid_fd)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 1731, in get_logind_session
    cgroup_file = os.open('cgroup', os.O_RDONLY, dir_fd=proc_pid_fd)
FileNotFoundError: [Errno 2] No such file or directory: 'cgroup'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of apt-xapian-index
error running python rtupdate hook apt-xapian-index
dpkg-query: package 'ibus' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of ibus
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 620, in add_proc_info
    ret = self.get_logind_session(pid, proc_pid_fd)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 1731, in get_logind_session
    cgroup_file = os.open('cgroup', os.O_RDONLY, dir_fd=proc_pid_fd)
FileNotFoundError: [Errno 2] No such file or directory: 'cgroup'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of ibus
error running python rtupdate hook ibus
dpkg-query: package 'kajongg' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of kajongg
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 620, in add_proc_info
    ret = self.get_logind_session(pid, proc_pid_fd)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 1731, in get_logind_session
    cgroup_file = os.open('cgroup', os.O_RDONLY, dir_fd=proc_pid_fd)
FileNotFoundError: [Errno 2] No such file or directory: 'cgroup'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of kajongg
error running python rtupdate hook kajongg
dpkg-query: package 'light-locker-settings' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of light-locker-settings
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 620, in add_proc_info
    ret = self.get_logind_session(pid, proc_pid_fd)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 1731, in get_logind_session
    cgroup_file = os.open('cgroup', os.O_RDONLY, dir_fd=proc_pid_fd)
FileNotFoundError: [Errno 2] No such file or directory: 'cgroup'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of light-locker-settings
error running python rtupdate hook light-locker-settings
dpkg-query: package 'system-config-printer-common' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of system-config-printer-common
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 620, in add_proc_info
    ret = self.get_logind_session(pid, proc_pid_fd)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 1731, in get_logind_session
    cgroup_file = os.open('cgroup', os.O_RDONLY, dir_fd=proc_pid_fd)
FileNotFoundError: [Errno 2] No such file or directory: 'cgroup'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of system-config-printer-common
error running python rtupdate hook system-config-printer-common
dpkg-query: package 'system-config-printer' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of system-config-printer
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 620, in add_proc_info
    ret = self.get_logind_session(pid, proc_pid_fd)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 1731, in get_logind_session
    cgroup_file = os.open('cgroup', os.O_RDONLY, dir_fd=proc_pid_fd)
FileNotFoundError: [Errno 2] No such file or directory: 'cgroup'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of system-config-printer
error running python rtupdate hook system-config-printer
dpkg-query: package 'virt-manager' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of virt-manager
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 109, in apport_excepthook
    pr.add_proc_info(extraenv=['PYTHONPATH', 'PYTHONHOME'])
  File "/usr/lib/python3/dist-packages/apport/report.py", line 620, in add_proc_info
    ret = self.get_logind_session(pid, proc_pid_fd)
  File "/usr/lib/python3/dist-packages/apport/report.py", line 1731, in get_logind_session
    cgroup_file = os.open('cgroup', os.O_RDONLY, dir_fd=proc_pid_fd)
FileNotFoundError: [Errno 2] No such file or directory: 'cgroup'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/py3clean", line 210, in <module>
    main()
  File "/usr/bin/py3clean", line 196, in main
    pfiles = set(dpf.from_package(options.package))
  File "/usr/share/python3/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of virt-manager
error running python rtupdate hook virt-manager
dpkg: error processing package python3 (--configure):
 installed python3 package post-installation script subprocess returned error exit status 4
dpkg: dependency problems prevent configuration of netplan.io:
 netplan.io depends on python3; however:
  Package python3 is not configured yet.

dpkg: error processing package netplan.io (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-six:
 python3-six depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package python3-six (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-gi:
 python3-gi depends on python3 (<< 3.9); however:
  Package python3 is not configured yet.
 python3-gi depends on python3 (>= 3.8~); however:
  Package python3 is not configured yet.
 python3-gi depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package python3-gi (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-netifaces:
 python3-netifaces depends on python3 (<< 3.9); however:
  Package python3 is not configured yet.
 python3-netifaces depends on python3 (>= 3.8~); however:
  Package python3 is not configured yet.

dpkg: error processing package python3-netifaces (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of ubuntu-advantage-tools:
 ubuntu-advantage-tools depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package ubuntu-advantage-tools (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of lsb-release:
 lsb-release depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package lsb-release (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-nacl:
 python3-nacl depends on python3 (>= 3~); however:
  Package python3 is not configured yet.
 python3-nacl depends on python3-six; however:
  Package python3-six is not configured yet.
 python3-nacl depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package python3-nacl (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-cffi-backend:
 python3-cffi-backend depends on python3 (<< 3.9); however:
  Package python3 is not configured yet.
 python3-cffi-backend depends on python3 (>= 3.8~); however:
  Package python3 is not configured yet.

dpkg: error processing package python3-cffi-backend (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-pkg-resources:
 python3-pkg-resources depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package python3-pkg-resources (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of networkd-dispatcher:
 networkd-dispatcher depends on python3-gi; however:
  Package python3-gi is not configured yet.
 networkd-dispatcher depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package networkd-dispatcher (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-dbus:
 python3-dbus depends on python3 (<< 3.9); however:
  Package python3 is not configured yet.
 python3-dbus depends on python3 (>= 3.8~); however:
  Package python3 is not configured yet.
 python3-dbus depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package python3-dbus (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-pymacaroons:
 python3-pymacaroons depends on python3-nacl (>= 1.1.2); however:
  Package python3-nacl is not configured yet.
 python3-pymacaroons depends on python3-six (>= 1.8.0); however:
  Package python3-six is not configured yet.
 python3-pymacaroons depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package python3-pymacaroons (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of ubuntu-minimal:
 ubuntu-minimal depends on lsb-release; however:
  Package lsb-release is not configured yet.
 ubuntu-minimal depends on netplan.io; however:
  Package netplan.io is not configured yet.
 ubuntu-minimal depends on python3; however:
  Package python3 is not configured yet.
 ubuntu-minimal depends on ubuntu-advantage-tools; however:
  Package ubuntu-advantage-tools is not configured yet.

dpkg: error processing package ubuntu-minimal (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python3-yaml:
 python3-yaml depends on python3 (<< 3.9); however:
  Package python3 is not configured yet.
 python3-yaml depends on python3 (>= 3.8~); however:
  Package python3 is not configured yet.
 python3-yaml depends on python3:any; however:
  Package python3 is not configured yet.

dpkg: error processing package python3-yaml (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 python3
 netplan.io
 python3-six
 python3-gi
 python3-netifaces
 ubuntu-advantage-tools
 lsb-release
 python3-nacl
 python3-cffi-backend
 python3-pkg-resources
 networkd-dispatcher
 python3-dbus
 python3-pymacaroons
 ubuntu-minimal
 python3-yaml
E: Sub-process /usr/bin/dpkg returned an error code (1)
linux-browser-installer: Error: 'apt install -y apt-transport-https curl' failed
```
